-- Up Migration
INSERT INTO public.employee_locations (kind, country, province, name, is_active)
VALUES
  ('province', 'Pakistan', NULL, 'Punjab', true),
  ('province', 'Pakistan', NULL, 'Sindh', true),
  ('province', 'Pakistan', NULL, 'Khyber Pakhtunkhwa', true),
  ('province', 'Pakistan', NULL, 'Balochistan', true),
  ('province', 'Pakistan', NULL, 'Islamabad Capital Territory', true),
  ('province', 'Pakistan', NULL, 'Gilgit-Baltistan', true),
  ('province', 'Pakistan', NULL, 'Azad Jammu and Kashmir', true),

  ('district', 'Pakistan', 'Punjab', 'Lahore', true),
  ('district', 'Pakistan', 'Punjab', 'Faisalabad', true),
  ('district', 'Pakistan', 'Punjab', 'Rawalpindi', true),
  ('district', 'Pakistan', 'Punjab', 'Multan', true),
  ('district', 'Pakistan', 'Punjab', 'Gujranwala', true),
  ('district', 'Pakistan', 'Punjab', 'Sialkot', true),
  ('district', 'Pakistan', 'Punjab', 'Sargodha', true),
  ('district', 'Pakistan', 'Punjab', 'Bahawalpur', true),
  ('district', 'Pakistan', 'Punjab', 'Sheikhupura', true),
  ('district', 'Pakistan', 'Punjab', 'Gujrat', true),
  ('district', 'Pakistan', 'Punjab', 'Sahiwal', true),
  ('district', 'Pakistan', 'Punjab', 'Kasur', true),
  ('district', 'Pakistan', 'Punjab', 'Okara', true),
  ('district', 'Pakistan', 'Punjab', 'Rahim Yar Khan', true),
  ('district', 'Pakistan', 'Punjab', 'Dera Ghazi Khan', true),
  ('district', 'Pakistan', 'Sindh', 'Karachi Central', true),
  ('district', 'Pakistan', 'Sindh', 'Karachi East', true),
  ('district', 'Pakistan', 'Sindh', 'Karachi South', true),
  ('district', 'Pakistan', 'Sindh', 'Karachi West', true),
  ('district', 'Pakistan', 'Sindh', 'Korangi', true),
  ('district', 'Pakistan', 'Sindh', 'Malir', true),
  ('district', 'Pakistan', 'Sindh', 'Hyderabad', true),
  ('district', 'Pakistan', 'Sindh', 'Sukkur', true),
  ('district', 'Pakistan', 'Sindh', 'Larkana', true),
  ('district', 'Pakistan', 'Sindh', 'Shaheed Benazirabad', true),
  ('district', 'Pakistan', 'Sindh', 'Mirpur Khas', true),
  ('district', 'Pakistan', 'Sindh', 'Dadu', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Peshawar', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Mardan', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Abbottabad', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Swat', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Kohat', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Bannu', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Dera Ismail Khan', true),
  ('district', 'Pakistan', 'Khyber Pakhtunkhwa', 'Mansehra', true),
  ('district', 'Pakistan', 'Balochistan', 'Quetta', true),
  ('district', 'Pakistan', 'Balochistan', 'Gwadar', true),
  ('district', 'Pakistan', 'Balochistan', 'Turbat', true),
  ('district', 'Pakistan', 'Balochistan', 'Khuzdar', true),
  ('district', 'Pakistan', 'Balochistan', 'Sibi', true),
  ('district', 'Pakistan', 'Balochistan', 'Zhob', true),
  ('district', 'Pakistan', 'Islamabad Capital Territory', 'Islamabad', true),
  ('district', 'Pakistan', 'Gilgit-Baltistan', 'Gilgit', true),
  ('district', 'Pakistan', 'Gilgit-Baltistan', 'Skardu', true),
  ('district', 'Pakistan', 'Gilgit-Baltistan', 'Hunza', true),
  ('district', 'Pakistan', 'Gilgit-Baltistan', 'Ghizer', true),
  ('district', 'Pakistan', 'Azad Jammu and Kashmir', 'Muzaffarabad', true),
  ('district', 'Pakistan', 'Azad Jammu and Kashmir', 'Mirpur', true),
  ('district', 'Pakistan', 'Azad Jammu and Kashmir', 'Kotli', true),
  ('district', 'Pakistan', 'Azad Jammu and Kashmir', 'Rawalakot', true),

  ('city', 'Pakistan', 'Punjab', 'Lahore', true),
  ('city', 'Pakistan', 'Punjab', 'Faisalabad', true),
  ('city', 'Pakistan', 'Punjab', 'Rawalpindi', true),
  ('city', 'Pakistan', 'Punjab', 'Multan', true),
  ('city', 'Pakistan', 'Punjab', 'Gujranwala', true),
  ('city', 'Pakistan', 'Punjab', 'Sialkot', true),
  ('city', 'Pakistan', 'Punjab', 'Sargodha', true),
  ('city', 'Pakistan', 'Punjab', 'Bahawalpur', true),
  ('city', 'Pakistan', 'Punjab', 'Sheikhupura', true),
  ('city', 'Pakistan', 'Punjab', 'Gujrat', true),
  ('city', 'Pakistan', 'Punjab', 'Sahiwal', true),
  ('city', 'Pakistan', 'Punjab', 'Kasur', true),
  ('city', 'Pakistan', 'Punjab', 'Okara', true),
  ('city', 'Pakistan', 'Punjab', 'Rahim Yar Khan', true),
  ('city', 'Pakistan', 'Punjab', 'Dera Ghazi Khan', true),
  ('city', 'Pakistan', 'Punjab', 'Jhelum', true),
  ('city', 'Pakistan', 'Punjab', 'Wah Cantt', true),
  ('city', 'Pakistan', 'Punjab', 'Murree', true),
  ('city', 'Pakistan', 'Sindh', 'Karachi', true),
  ('city', 'Pakistan', 'Sindh', 'Hyderabad', true),
  ('city', 'Pakistan', 'Sindh', 'Sukkur', true),
  ('city', 'Pakistan', 'Sindh', 'Larkana', true),
  ('city', 'Pakistan', 'Sindh', 'Nawabshah', true),
  ('city', 'Pakistan', 'Sindh', 'Mirpur Khas', true),
  ('city', 'Pakistan', 'Sindh', 'Dadu', true),
  ('city', 'Pakistan', 'Sindh', 'Thatta', true),
  ('city', 'Pakistan', 'Sindh', 'Badin', true),
  ('city', 'Pakistan', 'Sindh', 'Jacobabad', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Peshawar', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Mardan', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Abbottabad', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Mingora', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Kohat', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Bannu', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Dera Ismail Khan', true),
  ('city', 'Pakistan', 'Khyber Pakhtunkhwa', 'Mansehra', true),
  ('city', 'Pakistan', 'Balochistan', 'Quetta', true),
  ('city', 'Pakistan', 'Balochistan', 'Gwadar', true),
  ('city', 'Pakistan', 'Balochistan', 'Turbat', true),
  ('city', 'Pakistan', 'Balochistan', 'Khuzdar', true),
  ('city', 'Pakistan', 'Balochistan', 'Sibi', true),
  ('city', 'Pakistan', 'Balochistan', 'Zhob', true),
  ('city', 'Pakistan', 'Islamabad Capital Territory', 'Islamabad', true),
  ('city', 'Pakistan', 'Gilgit-Baltistan', 'Gilgit', true),
  ('city', 'Pakistan', 'Gilgit-Baltistan', 'Skardu', true),
  ('city', 'Pakistan', 'Gilgit-Baltistan', 'Hunza', true),
  ('city', 'Pakistan', 'Azad Jammu and Kashmir', 'Muzaffarabad', true),
  ('city', 'Pakistan', 'Azad Jammu and Kashmir', 'Mirpur', true),
  ('city', 'Pakistan', 'Azad Jammu and Kashmir', 'Kotli', true),
  ('city', 'Pakistan', 'Azad Jammu and Kashmir', 'Rawalakot', true),

  ('town', 'Pakistan', 'Punjab', 'Gulberg', true),
  ('town', 'Pakistan', 'Punjab', 'Model Town', true),
  ('town', 'Pakistan', 'Punjab', 'Johar Town', true),
  ('town', 'Pakistan', 'Punjab', 'DHA Lahore', true),
  ('town', 'Pakistan', 'Punjab', 'Bahria Town Lahore', true),
  ('town', 'Pakistan', 'Punjab', 'Cantt Lahore', true),
  ('town', 'Pakistan', 'Punjab', 'Iqbal Town', true),
  ('town', 'Pakistan', 'Punjab', 'Satellite Town Rawalpindi', true),
  ('town', 'Pakistan', 'Punjab', 'Bahria Town Rawalpindi', true),
  ('town', 'Pakistan', 'Punjab', 'DHA Multan', true),
  ('town', 'Pakistan', 'Punjab', 'Peoples Colony Faisalabad', true),
  ('town', 'Pakistan', 'Punjab', 'Madina Town Faisalabad', true),
  ('town', 'Pakistan', 'Sindh', 'Clifton', true),
  ('town', 'Pakistan', 'Sindh', 'DHA Karachi', true),
  ('town', 'Pakistan', 'Sindh', 'Gulshan-e-Iqbal', true),
  ('town', 'Pakistan', 'Sindh', 'North Nazimabad', true),
  ('town', 'Pakistan', 'Sindh', 'PECHS', true),
  ('town', 'Pakistan', 'Sindh', 'Korangi', true),
  ('town', 'Pakistan', 'Sindh', 'Latifabad Hyderabad', true),
  ('town', 'Pakistan', 'Sindh', 'Qasimabad Hyderabad', true),
  ('town', 'Pakistan', 'Khyber Pakhtunkhwa', 'Hayatabad', true),
  ('town', 'Pakistan', 'Khyber Pakhtunkhwa', 'University Town Peshawar', true),
  ('town', 'Pakistan', 'Khyber Pakhtunkhwa', 'Cantt Peshawar', true),
  ('town', 'Pakistan', 'Khyber Pakhtunkhwa', 'Phase 5 Hayatabad', true),
  ('town', 'Pakistan', 'Balochistan', 'Jinnah Town Quetta', true),
  ('town', 'Pakistan', 'Balochistan', 'Satellite Town Quetta', true),
  ('town', 'Pakistan', 'Balochistan', 'Cantt Quetta', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'G-6', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'G-9', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'G-10', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'F-7', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'F-8', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'F-10', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'Blue Area', true),
  ('town', 'Pakistan', 'Islamabad Capital Territory', 'DHA Islamabad', true),
  ('town', 'Pakistan', 'Gilgit-Baltistan', 'Jutial Gilgit', true),
  ('town', 'Pakistan', 'Gilgit-Baltistan', 'Konodas Gilgit', true),
  ('town', 'Pakistan', 'Gilgit-Baltistan', 'Hussainabad Skardu', true),
  ('town', 'Pakistan', 'Azad Jammu and Kashmir', 'Upper Chattar', true),
  ('town', 'Pakistan', 'Azad Jammu and Kashmir', 'Chattar Muzaffarabad', true),
  ('town', 'Pakistan', 'Azad Jammu and Kashmir', 'New Mirpur City', true)
ON CONFLICT DO NOTHING;

-- Down Migration
DELETE FROM public.employee_locations
WHERE country = 'Pakistan'
  AND (
    (kind = 'district' AND name IN (
      'Gujrat', 'Sahiwal', 'Kasur', 'Okara', 'Rahim Yar Khan', 'Dera Ghazi Khan',
      'Karachi South', 'Karachi West', 'Korangi', 'Malir', 'Shaheed Benazirabad',
      'Mirpur Khas', 'Dadu', 'Kohat', 'Bannu', 'Dera Ismail Khan', 'Mansehra',
      'Khuzdar', 'Sibi', 'Zhob', 'Hunza', 'Ghizer', 'Kotli', 'Rawalakot'
    ))
    OR (kind = 'city' AND name IN (
      'Gujrat', 'Sahiwal', 'Kasur', 'Okara', 'Rahim Yar Khan', 'Dera Ghazi Khan',
      'Jhelum', 'Wah Cantt', 'Murree', 'Mirpur Khas', 'Dadu', 'Thatta', 'Badin',
      'Jacobabad', 'Mingora', 'Kohat', 'Bannu', 'Dera Ismail Khan', 'Mansehra',
      'Khuzdar', 'Sibi', 'Zhob', 'Hunza', 'Kotli', 'Rawalakot'
    ))
    OR (kind = 'town' AND name IN (
      'DHA Lahore', 'Bahria Town Lahore', 'Cantt Lahore', 'Iqbal Town',
      'Satellite Town Rawalpindi', 'Bahria Town Rawalpindi', 'DHA Multan',
      'Peoples Colony Faisalabad', 'Madina Town Faisalabad', 'DHA Karachi',
      'North Nazimabad', 'PECHS', 'Korangi', 'Latifabad Hyderabad',
      'Qasimabad Hyderabad', 'Hayatabad', 'University Town Peshawar',
      'Cantt Peshawar', 'Phase 5 Hayatabad', 'Jinnah Town Quetta',
      'Satellite Town Quetta', 'Cantt Quetta', 'G-6', 'G-10', 'F-7', 'F-8',
      'Blue Area', 'DHA Islamabad', 'Jutial Gilgit', 'Konodas Gilgit',
      'Hussainabad Skardu', 'Upper Chattar', 'Chattar Muzaffarabad',
      'New Mirpur City'
    ))
  );
